### ISSUE TITLE
Failure backing up Organization

### ISSUE THREAD

**Issue by jheaddings** [WaelHamze/xrm-ci-framework#167]
We are getting an error when trying to run the MSCRM Backup Online Instance. The organization we are trying to backup is a v9 organization and we can run the backup manually, but not using this task....

> 2018-10-08T22:52:29.4388146Z ##[section]Starting: Backup https://[actual Instance Name].crm.dynamics.com
> 2018-10-08T22:52:29.4394748Z ==============================================================================
> 2018-10-08T22:52:29.4394927Z Task         : MSCRM Backup Online Instance
> 2018-10-08T22:52:29.4395197Z Description  : Creates a backup of a Dynamics 365 Customer Engagement Online Instance
> 2018-10-08T22:52:29.4395356Z Version      : 9.0.3
> 2018-10-08T22:52:29.4395471Z Author       : Wael Hamze
> 2018-10-08T22:52:29.4395628Z Help         : This task uses the Microsoft.Xrm.OnlineManagementAPI: https://www.powershellgallery.com/packages/Microsoft.Xrm.OnlineManagementAPI
> 2018-10-08T22:52:29.4395828Z ==============================================================================
> **2018-10-08T22:52:33.2118176Z ##[error]Object reference not set to an instance of an object.**
> 2018-10-08T22:52:33.2495827Z ##[section]Finishing: Backup https://[actual Instance Name].crm.dynamics.com

![image](https://user-images.githubusercontent.com/40869725/46637955-fd06e880-cb0a-11e8-81d2-e2e730f16211.png)

**Comment by craigseymour** [comment]
@jheaddings we've seen the same behaviour, albeit for v8.2 instances.  One of our DevOps found the article linked below which might be a clue, but I've not had time to investigate.  Like you, we've resorted to disabling the Backup task in the pipeline, and doing it manually instead

https://developercommunity.visualstudio.com/content/problem/203534/all-builds-failing-with-object-reference-not-set-t.html

**Comment by WaelHamze** [comment]
I hear is this getting fixed by the vendor soon. I'll update you as soon I am able to take a back up again

**Comment by craigseymour** [comment]
Thanks for the update, @WaelHamze

**Comment by stephenacrown** [comment]
@WaelHamze @cseymr @jheaddings 

After reporting the same issue with Microsoft (Backup of v9 Dyn365 CE environment via API fails with InternalServerError in both zure DevOps pipeline and manually via powershell on my own machine):

![image](https://user-images.githubusercontent.com/38353501/48072813-47948700-e1d5-11e8-8c06-9715dee75b1f.png)

I've had this back today from Microsoft:
 
>    As discussed with you, as we have found the error was due to an recently identified  known bug, we have already notified product team on this and we were  working towards a fix on this issue.
I shall keep you posted with the fix progress on the reported behavior.
Please let me know if you have any concerns.

I did have a call from Microsoft on Friday November 2nd and they said they were targetting the next release (I do hope they meant minor release!) for a fix...

I've said we want the case left open so we can hassle them to get more info, and will post back here with that.

cc @VericaHodder

**Comment by jheaddings** [comment]
Good work @stephenacrown! Thanks for the information!

**Comment by stephenacrown** [comment]
Latest update:

>My name is <redacted> and I have been recently assigned to your case 118103021001596 to give you periodic feedback on your service request status and keep you updated of any change your ticket may incur during this process.        
Following on <redacted> last communication I would like to inform you that our Product Group is actively working on this issue, which means that for the time being we still don't have an official ETA to provide.  
From my side, be assured I will track this issue down regularly and if there aren´t any updates in the meantime, I will contact you back on the 4th of December with further feedback on this ticket.

**Comment by stephenacrown** [comment]
Latest update:

>Following on our previous email, be kindly advised **the issue is now fixed** and if all goes as planned the **upgrade should be complete** within a few weeks’ time **by the beginning of Decembe**r.

>Considering the above, be assured I am tracking this down closely and I will get back to you on the 10th of December or as soon as I have further news on the expected delivery.

**Comment by stephenacrown** [comment]
I had this email yesterday:

>I am very pleased to inform the solution to which this request pertains has been uploaded during this weekend into the organization provided as so I would like to inquire if the issue initially scoped for this case is still being felt?         
We  honestly trust the upgrades went well while the solution for the scope was provided, even though, we would like to have some feedback from your side so we can proceed and archive this particular ticket.   

And having just tested, it seems to be working now:

![image](https://user-images.githubusercontent.com/38353501/49789828-d3de2080-fd24-11e8-8ff6-71c298fae81a.png)


![image](https://user-images.githubusercontent.com/38353501/49789643-692ce500-fd24-11e8-8b9b-efedde28e8b4.png)

Suggest this Issue is now closed (as are any related to this)

@jheaddings @WaelHamze @vericahodder

**Comment by WaelHamze** [comment]
@stephenacrown thanks for the update. I am still getting authentication issues in my tenant so waiting on MS support to advise. Let's close this case for now and re-open if needed.

Thanks all for your collaboration on this.

Now we need the restore working :)
