### ISSUE TITLE
Error in Import Solution Task (Related to issue #3)

### ISSUE THREAD

**Issue by namurdock** [WaelHamze/xrm-ci-framework#9]
Sorry,, posted this against a closed issue, not sure if you would like to reopen or address separately...)

I am also getting a failure on import of a solution into 2016 onpremise system via the import solution deploy task in VSTS. When I go into CRM the solution is in there and fine. Attached is the import manifest which appears fine.

The issue seems to be there if I select holding solution or not. (if I do select holding solution then the upgrade is not applied and I have to manually go into CRM and apply the upgrade, which works fine)

Extract from debug log in Visual Studio Online:

2017-02-07T13:39:24.9134554Z ##[debug]StatusCode: 20

2017-02-07T13:39:39.9179378Z ##[debug]Sleeping for 15 seconds

2017-02-07T13:39:39.9540720Z ##[debug]StatusCode: 20

2017-02-07T13:39:54.9554122Z ##[debug]Sleeping for 15 seconds

2017-02-07T13:39:57.4113097Z ##[debug]StatusCode: 30

2017-02-07T13:39:57.4259572Z ##[debug]C:\agent_work\r1\a\PaymentsCore Build\Payments\Payments_managed.zip Imported Completed 034330cb-b98c-4ee9-ad04-7abb15c54d53

2017-02-07T13:39:57.4259572Z Solution Import Completed. Import Job Id: 034330cb-b98c-4ee9-ad04-7abb15c54d53

2017-02-07T13:39:57.4327927Z ##[debug]Downloading Solution Import Log for: 034330cb-b98c-4ee9-ad04-7abb15c54d53

2017-02-07T13:39:57.8077687Z ##[debug]Solution Import Log Downloaded Successfully

2017-02-07T13:39:57.8888182Z ##[debug]Import Progress: 92.436974789916

2017-02-07T13:39:57.9005362Z ##[debug]Import Result: success

2017-02-07T13:39:57.9005362Z ##[debug]Import Error Text:

2017-02-07T13:39:57.9181132Z ##[debug]<importexportxml .. (SEE ATTACHED FILE)

2017-02-07T13:39:58.0255282Z ##[debug]Caught exception from task script.

2017-02-07T13:39:58.0313872Z ##[debug]Error record:

2017-02-07T13:39:58.1407552Z ##[debug]Import Failed

2017-02-07T13:39:58.1427082Z ##[debug]At C:\agent_work_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.1\ps_modules\xRMCIFramework\ImportSolution.ps1:98 char:9

2017-02-07T13:39:58.1456377Z ##[debug]+ throw "Import Failed"

2017-02-07T13:39:58.1475907Z ##[debug]+ ~

2017-02-07T13:39:58.1485672Z ##[debug] + CategoryInfo : OperationStopped: (Import Failed:String) [], Run timeException

2017-02-07T13:39:58.1505202Z ##[debug] + FullyQualifiedErrorId : Import Failed

2017-02-07T13:39:58.1573557Z ##[debug]

2017-02-07T13:39:58.1651677Z ##[debug]Script stack trace:

2017-02-07T13:39:58.1768857Z ##[debug]at , C:\agent_work_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.1\ps_modules\xRMCIFramework\ImportSolution.ps1: line 98

2017-02-07T13:39:58.1788387Z ##[debug]at , C:\agent_work_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.1\MSCRMImportSolution.ps1: line 43

2017-02-07T13:39:58.1817682Z ##[debug]at , : line 1

2017-02-07T13:39:58.1837212Z ##[debug]at , : line 22

2017-02-07T13:39:58.1846977Z ##[debug]at , : line 18

2017-02-07T13:39:58.1876272Z ##[debug]at , : line 1

2017-02-07T13:39:58.1876272Z ##[debug]Exception:

2017-02-07T13:39:58.2091102Z ##[debug]System.Management.Automation.RuntimeException: Import Failed

2017-02-07T13:39:58.2725827Z ##[error]Import Failed

2017-02-07T13:39:58.2725827Z ##[debug]Processed: ##vso[task.logissue type=error]Import Failed

2017-02-07T13:39:58.2794182Z ##[debug]Processed: ##vso[task.complete result=Failed]

2017-02-07T13:39:58.3038307Z ##[section]Finishing: MSCRM Import Solution

[importLog.txt](https://github.com/WaelHamze/xrm-ci-framework/files/766803/importLog.txt)

**Comment by clc136** [comment]
May I suggest you try importing the solution manually and check the import log to see if import 100% or not? I have noticed when components already exist it can be less than 100% even when import is successful. I believe this is reported as failure by deploy task. Thanks Chris

**Comment by ikurtev** [comment]
This is a good point. When I was Solution Imports, I had to remove that check because very frequently the completion percentage is somewhere in the 90% even though the solution imports successfully. Instead I implemented a check to loop through the Xml log file and look for any components that have a result="failure" because that is a much better indicator of the success of the solution import. I will submit a pull request with my changes to Wael.

**Comment by ikurtev** [comment]
OK, I've added a change to ImportSolution.ps1 to my open pull request.

**Comment by namurdock** [comment]
Hi @WaelHamze any chance of an updated collection of build/release actions for 365 to use on Visual Studio online?

Or just some pointers on how to build my own from the pending changes @ikurtev ?

**Comment by WaelHamze** [comment]
Hi, I have merged the pull request and updated the Visual Studio Market place with the latest changes. Give it a go and let us know if this work now...

**Comment by namurdock** [comment]
Many thanks Wael. I am not sure I am seeing the updated version in the marketplace. It appears to be .16 still? I may have missed remembered the version number though.

**Comment by WaelHamze** [comment]
It should be there 8.0.15 is the latest

**Comment by namurdock** [comment]
Thanks Wael (quite rights), I have moved to an on prem agent so it builds a bit more reliably. However i am still getting an error, slightly different though:

[3_MSCRM Import Solution.txt](https://github.com/WaelHamze/xrm-ci-framework/files/796108/3_MSCRM.Import.Solution.txt)

The import now seems to return a success but still fails. The upgrade solution is imported but not applied in the CRM system.

**Comment by ikurtev** [comment]
OK, from the importexportxml, it appears that all components were processed and the result shows as success on all of them. The error is thrown from the part of the script that compares the solution version of the ZIP file (in solution.xml) to the solution version in CRM after the import has completed. @namurdock, can you log in CRM and check what is the version of the solution now? From the importexportxml, the solution verion appears to be 1.4.0.10. @WaelHamze, we may need to consider tweaking the comparison or removing it as well, something must be slightly off there.

**Comment by namurdock** [comment]
Is the issue due to me indicating that i want to use a holding solution, so in this instance the solution being imported in called Payments.

So a payments_upgrade solution is created in the system. This has the new version number.
The solution payments has the old number still.

If there is a check on the version number is it checking the holding solution or the original solution?

in this care the original was v 1.4.0.7 and i was upgrading to 1.4.0.10.

Do you know if the holding solution feature works correctly?

**Comment by namurdock** [comment]
BTW my powershell is ok, so if you want me to just test using powershell and changes to the importsolution.ps1 locally just let me know and i will contribute my findings.

**Comment by ikurtev** [comment]
@namurdock oh, I see. I strongly suggest you set up a Package Deployer Package and then use MSCRMPackageDeployer step to perform a managed solution upgrade. The package deployer contains all the logic necessary to complete that task. Even if we suppress this error with the version,  you'd still have to manually apply the solution upgrade after importing the holding solution which defeats the purpose of the automation. An on-premise agent will be helpful in this case because you'll want to be able to easily get your hands on the Package Deployer log file.

**Comment by namurdock** [comment]
ah ha! ergh... there was me hoping for an export from A import to B kind of thing.

So i will have to create a build template to package the solution for my build prior to the release kicking in then.

Doesn't seem to be much use in having the ability to import a holding solution if the script can't then apply the solution. 

According to this... https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/pull/123/commits/11fad840d61892ab5f9771c6fd95d25b87bcbeba

DeleteAndPromote-CrmSolution 

was introduced to apply the upgrade.

I Guess this would also be required in order to make use of the patching functionality to.
